import {ColorTypes} from './types';

export const colors: ColorTypes = {
  foreground: {
    primary: '#776897',
    white: '#fdfdfd',
    secondary: '#3F72AF',
    accent: '#2da3a0',
    text: '#0c0c0d',
    danger: '#f80726',
    lightText: '#6f6e72',
    bodyLight: '#979797',
    title: '#000000',
    star: '#fae005',
  },
  background: {
    app: '#ededed',
    transparent: 'transparent',
    appSecondary: '#ffffff',
    primary: '#fafafa',
    loading: 'rgba(237, 237, 237, 0.6)',
    secondary: '#e0e0e0',
    disabled: '#adadad',
    accent: '#f3f3f3',
    buttonPrimary: '#2da3a0',
    buttonSecondary: '',
    buttonAccent: '#EBC91E',
    buttonPressedPrimary: '#7adad7',
    skeleton: '#bfbfbf',
    buttonPressedSecondary: '#baeceb',
    buttonPressedAccent: '#46ccc9',
  },
  white: '#ffffff',
  border: '#3f3f3e',
};
